import lasio


mnemonic_dict = {
    'Vp': ['Vp', 'SVEL'],
    'DTL': ['DTL', 'DTSS'],
    'ОЭМКЗ_2': ['ориг. обознач.1', 'R15P (C15P)', 'R15PC (C15PC)', 'R20P (C20P)', 'R20PC (C20PC)', 'R24P (C24P)', 'R24PC (C24PC)', 'ESP', 'SESP', 'UL2P', 'UU2P', 'R25P (C25P)'],
    'ДТp': ['DTP', 'DT', 'DT1', 'DT2'],
    'Vs': ['Vs', 'SSVE'],
    'ОЭМКЗ_4': ['ориг. обознач.1', 'R39A (C39A)', 'R39AC (C39AC)', 'R42A (C42A)', 'R42AC (C42AC)', 'R44A (C44A)', 'R44AC (C44AC)', 'EDC', 'SEDC'],
    '2ЭМКЗ_1': ['ориг. обознач.1', 'A10H (A10H_COND)', 'A10H_UNC', 'A10L (A10L_COND)', 'A10L_UNC илиA16H (A16H_COND)', 'A16H_UNC', 'A16L (A16L_COND)', 'A16L_UNC', 'P112', 'P114', 'P212', 'P214', 'RSAH', 'RSAL'],
    'DTSt': ['DTSt', 'DTST', 'DTST', 'DTST'],
    'DTS': ['DTS', 'DTS', 'DTSM', 'DTSF', 'DTS'],
    'ОЭМК': ['ориг. обознач.1', 'EWC', 'SEWC', 'P1UP', 'P1DN', 'P2UP', 'P2DN ', 'EWC', 'SEWC'],
    'DTP': ['DTP', 'DTPX', 'DTPX', 'DTC', 'DTCO', 'DTC (DT)', 'DTP'],
    '3ЭМКЗ_5': ['ориг. обознач.1', 'A48H', 'A48M', 'A48L', 'P48H1', 'P48H2', 'P48M1', 'P48M2', 'P48L1', 'P48L2'],
    '3ЭМКЗ_4': ['ориг. обознач.1', 'P40H1', 'P40H2', 'P40M1', 'P40M2', 'P40L1', 'P40L2', 'RH40A (CH40A)', 'RH40AC (CH40AC)', 'RM40A (CM40A)', 'RM40AC (CM40AC)', 'RL40A (CL40A)', 'RL40AC (CL40AC)'],
    '3ЭМКЗ_3': ['ориг. обознач.1', 'A32H', 'A32M', 'A32L', 'P32H1', 'P32H2', 'P32M1', 'P32M2', 'P32L1', 'P32L2'],
    '3ЭМКЗ_2': ['ориг. обознач.1', 'P24H1', 'P24H2', 'P24M1', 'P24M2', 'P24L1', 'P24L2', 'RH24A (CH24A)', 'RH24AC (CH24AC)', 'RM24A (CM24A)', 'RM24AC (CM24AC)', 'RL24A (CL24A)', 'RL24AC (CL24AC)'],
    '3ЭМКЗ_1': ['ориг. обознач.1', 'P16H1', 'P16H2', 'P16M1', 'P16M2', 'P16L1', 'P16L2', 'RH16P (CH16P)', 'RH16PC (CH16PC)', 'RM16P (CM16P)', 'RM16PC (CM16PC)', 'RL16P (CL16P)', 'RL16PC (CL16PC)'],
    '2ЭМКЗ_5': ['ориг. обознач.1', 'RACHM', 'RACLM', 'P152', 'P154', 'P252', 'P254', 'A34H (A34H_COND)', 'A34H_UNC', 'A34L (A34L_COND)', 'A34L_UNC илиA40H (A40H_COND)', 'A40H_UNC', 'A40L (A40L_COND)', 'A40L_UNC', 'RDAH', 'RDAL'],
    '2ЭМКЗ_4': ['ориг. обознач.1', 'P142', 'P144', 'P242', 'P244'],
    '2ЭМКЗ_3': ['ориг. обознач.1', 'P132', 'P134', 'P232', 'P234'],
    '2ЭМКЗ_2': ['ориг. обознач.1', 'P122', 'P124', 'P222', 'P224', 'P16H (P16H_COND)', 'P16H_UNC', 'P16L (P16L_COND)', 'P16L_UNC илиP22H (P22H_COND)', 'P22H_UNC', 'P22L (P22L_COND)', 'P22L_UNC'],
    'ОЭМКЗ_1': ['ориг. обознач.1', 'R09A (C09A)', 'R09AC (C09AC)', 'R12A (C12A)', 'R12AC (C12A)', 'R18A (C18A)', 'R18AC (C18AC)', 'EXC', 'SEXC', 'UL1P', 'UU1P', 'R15A (C15A)'],
    '2ЭМК': ['ориг. обознач.1'],
    '3ЭМКЗА_1': ['ориг. обознач.1'],
    '3ЭМКЗА_2': ['ориг. обознач.1'],
    '3ЭМКЗА_3': ['ориг. обознач.1'],
    '3ЭМКЗА_4': ['ориг. обознач.1'],
    '3ЭМКЗА_5': ['ориг. обознач.1'],
    'A1p': ['A1p'],
    'A2p': ['A2p'],
    'AL1-16': ['AL1-16'],
    'AL1-8': ['AL1-8'],
    'AP1': ['AP1'],
    'AP1-16': ['AP1-16'],
    'AP1-8': ['AP1-8', 'EERP'],
    'AP2': ['AP2'],
    'AS1-16': ['AS1-16'],
    'AS1-8': ['AS1-8', 'EERS'],
    'ASt1-16': ['ASt1-16'],
    'ASt1-8': ['ASt1-8'],
    'A_САТ': ['A_ATW', 'AMWF'],
    'AГГК-Пб': ['AGGB', 'ADLA1-ADLA16', 'ALFDA', 'RLSC'],
    'AГГК-Пм': ['AGGM', 'ADSA1-ADSA16', 'ALNDA', 'RSSC'],
    'AИК': ['AIK'],
    'AИКб': ['AIKB', 'AFCD', 'AFCDC', 'АИКЗб', 'AIKZb'],
    'AИКм': ['AIKM', 'AFCS', 'AFCSC', 'АИКЗм', 'AIKZm'],
    'AИКс': ['AIKS', 'AFCM', 'AFCMC', 'АИКЗс', 'AIKZs'],
    'BETA': ['BETA'],
    'DEKL': ['DEKL'],
    'DEKP': ['DEKP'],
    'DEKS': ['DEKS'],
    'DEKSt': ['DEKSt'],
    'DАГГК': ['DAGGP'],
    'DГГК': ['DGGP', 'SDRO'],
    'E': ['E'],
    'G': ['G'],
    'KBR': ['KBR'],
    'Pk': ['Pk'],
    'Pе': ['Pe', 'PE', 'DPEM', 'DPEFM', 'ALPELC', 'PEF', 'HPEF', 'ULDS', 'NPE', 'FPE', 'PDPE', 'PEDF', 'PEDN', 'PE'],
    'T1': ['T1'],
    'T1_1': ['T1_1'],
    'T1p': ['T1p'],
    'T2p': ['T2p'],
    'TL1-16': ['TL1-16'],
    'TL1-8': ['TL1-8'],
    'TP1': ['TP1', 'TT1'],
    'TP1-16': ['TP1-16', 'TTC'],
    'TP1-8': ['TP1-8', 'TTC', 'TTRP', 'T1'],
    'TP2': ['TP2', 'TT2'],
    'TS1-16': ['TS1-16', 'TTS'],
    'TS1-8': ['TS1-8', 'TTS', 'TTRS', 'T2'],
    'TSt1-16': ['TSt1-16', 'TTST'],
    'TSt1-8': ['TSt1-8', 'TTST'],
    'T_САТ': ['T_ATW', 'TTWF'],
    'U1': ['U1'],
    'U1_1': ['U1_1'],
    'U2': ['U2'],
    'U2_1': ['U2_1'],
    'U3': ['U3'],
    'U3_1': ['U3_1'],
    'VL': ['VL'],
    'VSt': ['VSt'],
    'WНГК': ['WNGK', 'NPBM'],
    'WННК-НТ': ['WNNKnt'],
    'WННК-Т': ['WNNKt', 'NPBM', 'TNPS', 'TNPL', 'NKTR', 'NRAT', 'TPOR'],
    'k': ['k'],
    'АPе': ['APe', 'APE1-APE16', 'ALPELC', 'Photoelectric Cross Section'],
    'АБК': ['ALL'],
    'АБКб': ['ALLD', 'AFRD (AFCD)', 'HLLD', 'HARD (HACD)', 'HAUD', 'HLDU'],
    'АБКм': ['ALLS', 'AFRS (AFCS)', 'HLLS', 'HARS (HACS)', 'HAUS', 'HLSU'],
    'АБКс': ['ALLM', 'AFRM (AFCM)'],
    'АГГК-ЛП': ['AGGLP', 'ALCDLC'],
    'АГГК-ЛПб': ['AGGLB'],
    'АГГК-ЛПм': ['AGGLM'],
    'АГГК-П': ['AGGP', 'ADRH1-ADRH16', 'ABDCM', 'ABDCDM', 'ABDCLM', 'ABDCRM', 'ABDCUM', 'ABDCF01-ABCDF16', 'ALCDA', 'ALCDHC', 'ROSC', 'RHOBA', 'Azimuthal Delta Rho - Sector1-16', 'Azimuthal Density'],
    'АГК': ['AGK', 'GRASM', 'GRBSM', 'GRCSM'],
    'АК': ['AL', 'AC', 'DAL', 'MAC', 'MAC2', 'BCS', 'BCSD', 'BCSBB', 'BCSBD', 'BCSFA', 'BCSHA', 'SLS', 'CSS', 'dT', 'Akdt', 'АКДТ', 'ak', 'Dt', 'ДТ', 'АКдт', 'Dtak', 'AKDT', 'дТр', 'DTp', 'DKP', 'AKp'],
    'АКШ': ['WAL', 'AC', 'LSS'],
    'БК': ['BK', 'DLL', 'HDLL ', 'DLL', 'LL', 'RFOC'],
    'БК3': ['BK3', 'LL3', 'LL3', 'LL3'],
    'БК7': ['BK7', 'LL7'],
    'БК9': ['BK9'],
    'БКЗ': ['BKZ'],
    'БКб': ['BKB', 'CLLD', 'MLR4', 'RD', 'LLD', ' CLLD', 'DLL', 'DDLL', 'БК-б', 'БК-бз', 'БКбз', 'BK-b', 'BK-bz', 'BKbz', 'RDD (RD)'],
    'БКм': ['BKM', 'CLLS', 'MLR1', 'MLR2', 'RS', 'LLS', 'SLL', 'DSLL', 'FEFR', 'FEFE', 'БК-м', 'БК-мз', 'БКмз', 'BK-m', 'BK-mz', 'BKmz', 'RS', 'RFOC'],
    'БКс': ['BKS', 'MLR3', 'MSF1', 'БК-с', 'БК-сз', 'БКсз', 'BK-s', 'BK-sz', 'BKsz', 'RD'],
    'БМК': ['BMK', 'MLL', 'CMLL', 'MLL', 'LLS', 'MLL', 'CMLL', 'MLL', 'MRRS', 'МБК', 'MBK', 'MSFL', 'RMLL'],
    'ВАК-КД': ['CDAL', 'XMAC', 'DSST', 'DSI'],
    'ВДК': ['EPL', 'PSDO', 'PSUP', 'EPT'],
    'ВДК_ф': ['EPL_p', 'EATT', 'EPS'],
    'ВИК05': ['IK05', 'DF05', 'ВИК05', 'УЭС05', 'VIK05', 'И1', 'ИК1', 'ИЗ1', 'ВИК1', 'ВИКИЗ1', 'I1', 'IK1', 'IZ1', 'VIK1', 'VIKIZ1', 'IKRK1', 'IK05', 'R0.5', 'RK0.5', 'RO0.5', 'RO05'],
    'ВИК06': ['IK06', 'DF06'],
    'ВИК07': ['IK07', 'DF07', 'ВИК07', 'УЭС07', 'VIK07', 'И2', 'ИК2', 'ИЗ2', 'ВИК2', 'ВИКИЗ2', 'I2', 'IK2', 'IZ2', 'VIK2', 'VIKIZ2', 'IKRK2', 'IK07', 'R0.7', 'RK0.7', 'RO0.7', 'RO07'],
    'ВИК08': ['IK08', 'DF08'],
    'ВИК10': ['IK10', 'DF10', 'ВИК10', 'УЭС10', 'VIK10', 'И3', 'ИК3', 'ИЗ3', 'ВИК3', 'ВИКИЗ3', 'I3', 'IK3', 'IZ3', 'VIK3', 'VIKIZ3', 'IKRK3', 'IK10', 'RO10'],
    'ВИК12': ['IK12', 'DF12'],
    'ВИК14': ['IK14', 'DF14', 'ВИК14', 'УЭС14', 'VIK14', 'И4', 'ИК4', 'ИЗ4', 'ВИК4', 'ВИКИЗ4', 'I4', 'IK4', 'IZ4', 'VIK4', 'VIKIZ4', 'IKRK4', 'IK14', 'RO14'],
    'ВИК16': ['IK16', 'DF16'],
    'ВИК20': ['IK20', 'DF20', 'ВИК14', 'УЭС14', 'VIK14', 'И5', 'ИК5', 'ИЗ5', 'ВИК5', 'ВИКИЗ5', 'I5', 'IK5', 'IZ5', 'VIK5', 'VIKIZ5', 'IKRK5', 'IK20', 'RO20'],
    'ВИКИЗ (ВЭМК)': ['VIKIZ (VEMKZ)'],
    'ВП': ['IPL'],
    'ГАК': ['GAL'],
    'ГГК-ЛП': ['GGLP', 'ZDL', 'ZDEN', 'BDCM', 'BDCUM', 'BDCFM,', 'ALCDLC', 'RHOM', 'BDC', 'DEN', 'ГГКЛП', 'ГГМ-ЛП', 'ГГМЛП', 'GGKLP', 'GGM-LP', 'GGMLP', 'RHOB'],
    'ГГК-ЛПб': ['GGLB', 'DLAM', 'DLAFM', 'TCRL', 'FW1-3', 'PDFC', 'Litho-Density GGL by Large Sonde'],
    'ГГК-ЛПм': ['GGLM', 'DSAM', 'DSAFM', 'TCRS', 'NW1-3', 'PDNC', 'Litho-Density GGL by Small Sonde'],
    'ГГК-П': ['GGP', 'DEN', 'DNC', 'BDCM', 'RHOB', 'ROBA', 'HRHO', 'NRHO', 'HNRH', 'RBD', 'DEN', 'ПЛ', 'ГГК', 'ГГМ', 'ГГКП', 'GGK', 'GGM', 'GGKP', 'DENS'],
    'ГГК-Пб': ['GGB', 'LDEN', 'DLAM', 'BLM', 'RHL', 'RHOL', 'HLHR', 'SSRH', 'CH3', 'CH4', 'DCRF', 'ГГКб', 'ГГКПб', 'GGKb', 'GGKPb', 'GGR1'],
    'ГГК-Пм': ['GGM', 'SDEN', 'DSAM', 'BSM', 'RHS', 'RHOS', 'HSHR', 'CH1', 'CH2', 'DCRN', 'ГГКм', 'ГГКПм', 'GGKm', 'GGKPm', 'GGR2'],
    'ГГК-С': ['SGGL', 'ГГК-С', 'ГГКС', 'ГГМ-С', 'ГГМС', 'GGK-S', 'GGKS', 'GGM-S', 'GGMS'],
    'ГЗ1': ['GZ1', 'КС1', 'A0.4M0.1N', 'A04M01N'],
    'ГЗ2': ['GZ2', 'КC2', 'A1.0M0.1N', 'A1M0.1N', 'A1M01N'],
    'ГЗ3': ['GZ3', 'КC3', 'A2.0M0.5N', 'A2M0.5N', 'А2М05N'],
    'ГЗ4': ['GZ4', 'КC4', 'A4.0M0.5N', 'A4M0.5N', 'A4M05N'],
    'ГЗ5': ['GZ5', 'КC5', 'A8.0M1.0N', 'A8M1N'],
    'ГК': ['GK', 'GR', 'GRAM', 'GRBM', 'GRCM', 'GRAFM', 'GRBFM', 'GRCFM', 'GR', 'PGGR', 'PGRC', 'DGRC', 'DGRCC', 'GR', 'HGR', 'GR_EDTC', 'GR', 'SGRC', 'GR', 'GRDI', 'ГМ', 'EGR', 'GAMM', 'GRC'],
    'ГНМ': ['GNL'],
    'ДВК': ['DVK'],
    'ДТМ': ['TGL'],
    'ИДК ': ['DL', 'DEL4', 'DEL2', 'DIEL', 'EPDC', 'DLOG'],
    'ИДК_а': ['DL_a'],
    'ИК': ['IK', '8И1.4', '7И1.6', '6Ф1', '6И0.8', '6Ф0.7', '4И3', '4И1.6', '4И1', '3И1', '8I1.4', '7I1.6', '6F1', '6I0.8', '6R0.8', '6F0.7', '4I3', '4R3', '4I1.6', '4R1.6', '4I1', '3I1', 'DIL', 'IK', 'CILS', 'RIK'],
    'ИК1': ['I1A', 'M0C1', 'M1C1', 'M2C1', 'M4C1', 'AOCO10', 'AOCB10', 'ATCO10', 'ATCB10', 'AFOCO10', 'AFCB10', 'AECO10', 'IK1'],
    'ИК2': ['I2A', 'M0C2', 'M1C2', 'M2C2', 'M4C2', 'AOCO20', 'AOCB20', 'ATCO20', 'ATCB20', 'AFOCO20', 'AFCB20', 'AECO20', 'IK2'],
    'ИК3': ['I3A', 'M0C3', 'M1C3', 'M2C3', 'M4C3', 'AOCO30', 'AOCB30', 'ATCO30', 'ATCB30', 'AFOCO30', 'AFCB30', 'AECO30', 'IK3'],
    'ИК4': ['I4A', 'M0C4', 'M1C4', 'M2C4', 'M4C4', 'AOCO60', 'AOCB60', 'ATCO60', 'ATCB60', 'AFOCO60', 'AFCB60', 'AECO60', 'IK4'],
    'ИК5': ['I5A', 'M0C5', 'M1C5', 'M2C5', 'M4C5', 'AOCO90', 'AOCB90', 'ATCO90', 'ATCB90', 'AFOCO90', 'AFCB90', 'AECO90', 'IK5'],
    'ИК6': ['I6A', 'M0C6', 'M1C6', 'M2C6', 'M4C6', 'IK6'],
    'ИКЗ': ['IKZ'],
    'ИКМПП': ['TRIL'],
    'ИКа': ['IKA', 'ILA', 'CILA'],
    'ИКб': ['IKB', 'CIRD', 'СILD', 'CIPD', 'CIDR', 'RILD', 'СILD', 'СILD', 'ИКб', 'ИКбз', 'IKb', 'IKbz', 'IKZb'],
    'ИКм': ['IKM', 'CILS', 'ИКм', 'ИКмз', 'IKm', 'Ikmz', 'IKZm'],
    'ИКр': ['IKR', 'ILR', 'CILR'],
    'ИКс': ['IKS', 'CIRM', 'СILM', 'CIPM', 'CIMR ', 'RILM', 'CILM', 'CILM', 'ИКс', 'ИКсз', 'IKs', 'IKsz', 'IKZs'],
    'ИНГК-С': ['INNK-S', 'CO', 'SS', 'TMDGR', 'CSNG', 'F1C', 'F1CA', 'F1FE', 'F1O', 'F1SI', 'F2CL,F2FE', 'F2GD', 'F2H', 'F2K', 'F2MG', 'F2TI', 'F2S ', 'N1C', 'N1CA', 'N1FE', 'N1O', 'N1SI', 'N2CA', 'N2CL', 'N2FE', 'N2GD', 'N2H', 'N2K', 'N2MG', 'N2S', 'N2SI', 'N2TI', 'ИНГМ', 'ИНГК', 'ИНГМ-С', 'INGK', 'PND', 'C/O каротаж'],
    'ИСФ': ['FFI'],
    'ИСФ_1': ['FFI_1', 'T2MFFI', 'CMFF', 'FFV', 'MFFI', 'динамическая пористость'],
    'КМВ': ['MSL', 'MAG', 'DMAG', 'MRIL'],
    'КМП': ['MNL'],
    'КПГП': ['TEPL'],
    'КСК': ['SEL'],
    'Калий': ['POTA', 'K', 'KAPI', 'GRK', 'POTA', 'POTA', 'HFK', 'GRPO', 'PO', 'GRPO'],
    'МГЗ': ['MGZ', 'MINV', 'MINV', 'MINV', 'MINV', 'MRS1', 'MRS2', 'MR1F', 'MR2F', 'МКЗгз', 'ГМЗ', 'GMZ', 'MGZ', 'RLML', 'A0.025M0.025N', 'A0025M0025N', 'A0.025M', 'A0025M'],
    'МК': ['MRL', 'МКЗ'],
    'МПЗ': ['MPZ', 'MNOR', 'MNOR', 'MNRL', 'МКЗпз', 'ПМЗ', 'PMZ', 'MPZ', 'RNML', 'А0.05M', 'А005M', 'A0.05M-N', 'A005M-N'],
    'НАК': ['NAL'],
    'НГК': ['NGK', 'NEU', 'NGK', 'NGR', 'НГК', 'HGR', 'нгк', 'HGK', 'NGк', 'ngk', 'NG'],
    'НГК-С': ['NGK-S', 'ECS'],
    'НГКб': ['NGB'],
    'НГКм': ['NGM'],
    'НГКс': ['NGS'],
    'ННК-НТ': ['NNKnt', 'CN', 'SWN', 'DSEN', 'ННМ-НТ', 'ННМ-Н', 'НК-Н', 'НКН', 'ENS'],
    'ННК-НТб': ['NNBnt', 'ННК-НТбз', 'ННКНТбз', 'ННКНТб', 'НКНТ-бз', 'НКНТбз', 'НКНТ-б', 'НКНТб', 'НК-НТб', 'NNK-NTbz', 'NNKNTbz', 'NNKNTb', 'NKNT-bz', 'NKNTbz', 'NKNT-b', 'NKNTb', 'NK-NTb', 'RFEN', 'RLTN', 'NFAR'],
    'ННК-НТм': ['NNMnt', 'ННК-НТмз', 'ННКНТмз', 'ННКНТм', 'НКНТ-мз', 'НКНТмз', 'НКНТ-м', 'НКНТм', 'НК-НТм', 'NNK-NTmz', 'NNKNTmz', 'NNKNTm', 'NKNT-mz', 'NKNTmz', 'NKNT-m', 'NKNTm', 'NK-NTm', 'RNEN', 'RSTN', 'NNEAR'],
    'ННК-Т': ['NNKt', 'CNT', 'TDS', 'ННМ-Т', 'ННМТ', 'НК-Т', 'НМТ', 'TDS'],
    'ННК-Тб': ['NNBt', 'NFBM', 'TNFA', 'FCNT', 'HCFT', 'RCFT', 'CFTC', 'NFA', 'DNFD', 'NCRF', 'TCRF', 'ННК-Тбз', 'ННКТбз', 'ННКТб', 'НКТ-бз', 'НКТбз', 'НКТ-б', 'НКТб', 'НК-Тб', 'HHK-бз', 'HHKбз', 'HHK-б', 'HHKб', 'NNK-Tbz', 'NNKTbz', 'NNKTb', 'NKT-bz', 'NKTbz', 'NKT-b', 'NKTb', 'NK-Tb', 'NNK-bz', 'NNKbz', 'NNK-b', 'NNKb', 'RFTN', 'DNFD', 'NFAR'],
    'ННК-Тм': ['NNMt', 'NNBM', 'TNNA', 'NCNT', 'HCNT', 'RCNT', 'CNTC', 'NNA', 'DNND', 'NCRN', 'TCRN', 'ННК-Тмз', 'ННКТмз', 'ННКТм', 'НКТ-мз', 'НКТмз', 'НКТ-м', 'НКТм', 'НК-Тм', 'HHK-мз', 'HHKмз', 'HHK-м', 'HHKм', 'NNK-Tmz', 'NNKTmz', 'NNKTm', 'NKT-mz', 'NKTmz', 'NKT-m', 'NKTm', 'NK-Tm', 'NNK-mz', 'NNKmz', 'NNK-m', 'NNKm', 'RNTN', 'DNND', 'NNEAR'],
    'ОГЗ': ['OGZ', 'КС6', 'KS6', 'ГЗО', 'GZO', 'ГЗК', 'GZR', 'OKS', 'GZKS', 'GZB', 'GZK3', 'GZ3R', 'GZ3B', 'GZ6', 'N0.5M2.0A', 'N0.5M2A', 'N05M2A'],
    'ОЭМКЗ_3': ['ориг. обознач.1', 'UL3P', 'UU3P'],
    'ОЭМКЗ_5': ['ориг. обознач.1', 'UL5P', 'UU5P', 'R55A (C55A)'],
    'ПЗ': ['PZ', 'КС', 'KS', 'N6.0M0.5A', 'N6M0.5A', 'N6M05A', 'N11.0M0.5A', 'N11M0.5A', 'N11M05A'],
    'ПС': ['PS', 'SP', 'SP', 'SP', 'SP', 'SPR', 'SPCG', 'SPDL', 'SPLL', 'SPRL', 'CGSP', 'СП', 'PS', 'RSP'],
    'ПСГ': ['SPGL'],
    'РРК': ['XR'],
    'Рез': ['REZ', 'DFRM', 'DPRM', 'AFMR', 'RMM5', 'MRES', 'MRES_SL', 'HICRS', 'ACRS', 'AHCRS', 'ASCRS ', 'RMSF', 'Рс', 'РЕЗИСТ', 'Rc', 'REZ', 'RES', 'RM', 'RT', 'RT_D', 'RB'],
    'САТ': ['ATW', 'BHTV'],
    'СБМК (ЭК-сканер)': ['MLLS', 'FMI'],
    'СГК': ['SGR', 'DSL', 'SL', 'PGGR', 'PGRC', 'SGR', 'SGR', 'ASGR', 'GRSG', 'ГКС', 'ГК-С', 'SGS'],
    'Ст1': ['S1', 'ИННМ', 'ИННК', 'ИННМ-Т'],
    'Т2': ['T2', 'MTDISTCM', 'T2DIS', 'T2_DIST'],
    'ТИК': ['TIL'],
    'ТМ': ['ТМ', 'TEMP'],
    'ТМЗ': ['TL']}


# In[6]:


def replace_encodings(codings, dictionary):
    reversed_dict = {}    
    for key, values in dictionary.items():
        for value in values:
            reversed_dict[value] = key        
    
    return [reversed_dict.get(code, code) for code in codings]

# Пример использования

def mnems(file_path):
    '''Возвращает в виде списка с кортежами новые мнемоники'''

    # Чтение файла .LAS
    las = lasio.read(file_path)

    # Вывод информации о файле
    mnemonics_list = [curve.mnemonic for curve in las.curves[1:]]

    return replace_encodings(mnemonics_list, mnemonic_dict)


print(mnems('/Users/polinanaydenova/ГИС+/Las/10_БК_fixed_charde.las'))

